name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Build (windows)
        if: matrix.os == 'ubuntu-latest'
        run: GOOS=windows GOARCH=amd64 go build ./...

      - name: Test
        run: go test -race ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13
